cd /Users/maria/Projects/spam2005-global/data_py/data_build_v2r0/data_out
cd /home/django/spam2005-global/data_py/data_build_v2r0/data_out/tiff

#server
declare -A crops=( ["acof"]="coffee_arabica" ["bana"]="banana" ["barl"]="barley" ["bean"]="bean" ["cass"]="cassava" ["chic"]="chickpea" ["cnut"]="coconut" ["coco"]="cocoa" ["cott"]="cotton" ["cowp"]="cowpea" ["grou"]="groundnut" ["lent"]="lentil" ["maiz"]="maize" ["ocer"]="cereals_other" ["ofib"]="fibers_other" ["oilp"]="oil_palm" ["ooil"]="oil_crops_other" ["opul"]="pulses_other" ["orts"]="roots_and_tubers_other" ["pige"]="pigeonpea" ["plnt"]="plantain" ["pmil"]="millet_pearl" ["pota"]="potato" ["rape"]="rapeseed" ["rcof"]="coffee_robusta" ["rest"]="rest_of_crops" ["rice"]="rice" ["sesa"]="sesame_seed" ["smil"]="millet_small" ["sorg"]="sorghum" ["soyb"]="soybean" ["sugb"]="sugar_beet" ["sugc"]="sugar_cane" ["sunf"]="sunflower" ["swpo"]="sweet_potato" ["teas"]="tea" ["temf"]="fruit_temperate" ["toba"]="tobacco" ["trof"]="fruit_tropical" ["vege"]="vegetable" ["whea"]="wheat" ["yams"]="yam" )

for i in whea rice maiz barl pmil smil sorg ocer pota swpo yams cass orts bean chic cowp pige lent opul soyb grou cnut oilp sunf rape sesa ooil sugc sugb cott ofib acof rcof coco teas toba bana plnt trof temf vege rest; do gdal_rasterize -a $i -te -180 -90 180 90 -ts 4320 2160 -a_srs EPSG:4326 -a_nodata -9999 -co "COMPRESS=LZW" -l spam2005v2r0_harvested_area PG:"dbname=djspamdata user=postgres" harvested-area/spam2005v2r0_harvested-area_${crops["${i:0:4}"]}_total.tiff; done;
for i in whea_i rice_i maiz_i barl_i pmil_i smil_i sorg_i ocer_i pota_i swpo_i yams_i cass_i orts_i bean_i chic_i cowp_i pige_i lent_i opul_i soyb_i grou_i cnut_i oilp_i sunf_i rape_i sesa_i ooil_i sugc_i sugb_i cott_i ofib_i acof_i rcof_i coco_i teas_i toba_i bana_i plnt_i trof_i temf_i vege_i rest_i ; do gdal_rasterize -a $i -te -180 -90 180 90 -ts 4320 2160 -a_srs EPSG:4326 -a_nodata -9999 -co "COMPRESS=LZW" -l spam2005v2r0_harvested_area PG:"dbname=djspamdata user=postgres" harvested-area/spam2005v2r0_harvested-area_${crops["${i:0:4}"]}_irrigated.tiff; done;
for i in whea_r rice_r maiz_r barl_r pmil_r smil_r sorg_r ocer_r pota_r swpo_r yams_r cass_r orts_r bean_r chic_r cowp_r pige_r lent_r opul_r soyb_r grou_r cnut_r oilp_r sunf_r rape_r sesa_r ooil_r sugc_r sugb_r cott_r ofib_r acof_r rcof_r coco_r teas_r toba_r bana_r plnt_r trof_r temf_r vege_r rest_r; do gdal_rasterize -a $i -te -180 -90 180 90 -ts 4320 2160 -a_srs EPSG:4326 -a_nodata -9999 -co "COMPRESS=LZW" -l spam2005v2r0_harvested_area PG:"dbname=djspamdata user=postgres" harvested-area/spam2005v2r0_harvested-area_${crops["${i:0:4}"]}_rainfed.tiff; done;

for i in whea rice maiz barl pmil smil sorg ocer pota swpo yams cass orts bean chic cowp pige lent opul soyb grou cnut oilp sunf rape sesa ooil sugc sugb cott ofib acof rcof coco teas toba bana plnt trof temf vege rest; do gdal_rasterize -a $i -te -180 -90 180 90 -ts 4320 2160 -a_srs EPSG:4326 -a_nodata -9999 -co "COMPRESS=LZW" -l spam2005v2r0_physical_area PG:"dbname=djspamdata user=postgres" physical-area/spam2005v2r0_physical-area_${crops["${i:0:4}"]}_total.tiff; done;
for i in whea_i rice_i maiz_i barl_i pmil_i smil_i sorg_i ocer_i pota_i swpo_i yams_i cass_i orts_i bean_i chic_i cowp_i pige_i lent_i opul_i soyb_i grou_i cnut_i oilp_i sunf_i rape_i sesa_i ooil_i sugc_i sugb_i cott_i ofib_i acof_i rcof_i coco_i teas_i toba_i bana_i plnt_i trof_i temf_i vege_i rest_i ; do gdal_rasterize -a $i -te -180 -90 180 90 -ts 4320 2160 -a_srs EPSG:4326 -a_nodata -9999 -co "COMPRESS=LZW" -l spam2005v2r0_physical_area PG:"dbname=djspamdata user=postgres" physical-area/spam2005v2r0_physical-area_${crops["${i:0:4}"]}_irrigated.tiff; done;
for i in whea_r rice_r maiz_r barl_r pmil_r smil_r sorg_r ocer_r pota_r swpo_r yams_r cass_r orts_r bean_r chic_r cowp_r pige_r lent_r opul_r soyb_r grou_r cnut_r oilp_r sunf_r rape_r sesa_r ooil_r sugc_r sugb_r cott_r ofib_r acof_r rcof_r coco_r teas_r toba_r bana_r plnt_r trof_r temf_r vege_r rest_r; do gdal_rasterize -a $i -te -180 -90 180 90 -ts 4320 2160 -a_srs EPSG:4326 -a_nodata -9999 -co "COMPRESS=LZW" -l spam2005v2r0_physical_area PG:"dbname=djspamdata user=postgres" physical-area/spam2005v2r0_physical-area_${crops["${i:0:4}"]}_rainfed.tiff; done;

for i in whea rice maiz barl pmil smil sorg ocer pota swpo yams cass orts bean chic cowp pige lent opul soyb grou cnut oilp sunf rape sesa ooil sugc sugb cott ofib acof rcof coco teas toba bana plnt trof temf vege rest; do gdal_rasterize -a $i -te -180 -90 180 90 -ts 4320 2160 -a_srs EPSG:4326 -a_nodata -9999 -co "COMPRESS=LZW" -l spam2005v2r0_production PG:"dbname=djspamdata user=postgres" production/spam2005v2r0_production_${crops["${i:0:4}"]}_total.tiff; done;
for i in whea_i rice_i maiz_i barl_i pmil_i smil_i sorg_i ocer_i pota_i swpo_i yams_i cass_i orts_i bean_i chic_i cowp_i pige_i lent_i opul_i soyb_i grou_i cnut_i oilp_i sunf_i rape_i sesa_i ooil_i sugc_i sugb_i cott_i ofib_i acof_i rcof_i coco_i teas_i toba_i bana_i plnt_i trof_i temf_i vege_i rest_i ; do gdal_rasterize -a $i -te -180 -90 180 90 -ts 4320 2160 -a_srs EPSG:4326 -a_nodata -9999 -co "COMPRESS=LZW" -l spam2005v2r0_production PG:"dbname=djspamdata user=postgres" production/spam2005v2r0_production_${crops["${i:0:4}"]}_irrigated.tiff; done;
for i in whea_r rice_r maiz_r barl_r pmil_r smil_r sorg_r ocer_r pota_r swpo_r yams_r cass_r orts_r bean_r chic_r cowp_r pige_r lent_r opul_r soyb_r grou_r cnut_r oilp_r sunf_r rape_r sesa_r ooil_r sugc_r sugb_r cott_r ofib_r acof_r rcof_r coco_r teas_r toba_r bana_r plnt_r trof_r temf_r vege_r rest_r; do gdal_rasterize -a $i -te -180 -90 180 90 -ts 4320 2160 -a_srs EPSG:4326 -a_nodata -9999 -co "COMPRESS=LZW" -l spam2005v2r0_production PG:"dbname=djspamdata user=postgres" production/spam2005v2r0_production_${crops["${i:0:4}"]}_rainfed.tiff; done;

for i in whea rice maiz barl pmil smil sorg ocer pota swpo yams cass orts bean chic cowp pige lent opul soyb grou cnut oilp sunf rape sesa ooil sugc sugb cott ofib acof rcof coco teas toba bana plnt trof temf vege rest; do gdal_rasterize -a $i -te -180 -90 180 90 -ts 4320 2160 -a_srs EPSG:4326 -a_nodata -9999 -co "COMPRESS=LZW" -l spam2005v2r0_yield PG:"dbname=djspamdata user=postgres" yield/spam2005v2r0_yield_${crops["${i:0:4}"]}_total.tiff; done;
for i in whea_i rice_i maiz_i barl_i pmil_i smil_i sorg_i ocer_i pota_i swpo_i yams_i cass_i orts_i bean_i chic_i cowp_i pige_i lent_i opul_i soyb_i grou_i cnut_i oilp_i sunf_i rape_i sesa_i ooil_i sugc_i sugb_i cott_i ofib_i acof_i rcof_i coco_i teas_i toba_i bana_i plnt_i trof_i temf_i vege_i rest_i ; do gdal_rasterize -a $i -te -180 -90 180 90 -ts 4320 2160 -a_srs EPSG:4326 -a_nodata -9999 -co "COMPRESS=LZW" -l spam2005v2r0_yield PG:"dbname=djspamdata user=postgres" yield/spam2005v2r0_yield_${crops["${i:0:4}"]}_irrigated.tiff; done;
for i in whea_r rice_r maiz_r barl_r pmil_r smil_r sorg_r ocer_r pota_r swpo_r yams_r cass_r orts_r bean_r chic_r cowp_r pige_r lent_r opul_r soyb_r grou_r cnut_r oilp_r sunf_r rape_r sesa_r ooil_r sugc_r sugb_r cott_r ofib_r acof_r rcof_r coco_r teas_r toba_r bana_r plnt_r trof_r temf_r vege_r rest_r; do gdal_rasterize -a $i -te -180 -90 180 90 -ts 4320 2160 -a_srs EPSG:4326 -a_nodata -9999 -co "COMPRESS=LZW" -l spam2005v2r0_yield PG:"dbname=djspamdata user=postgres" yield/spam2005v2r0_yield_${crops["${i:0:4}"]}_rainfed.tiff; done;

for i in whea rice maiz barl pmil smil sorg ocer pota swpo yams cass orts bean chic cowp pige lent opul soyb grou cnut oilp sunf rape sesa ooil sugc sugb cott ofib acof rcof coco teas toba bana plnt trof temf vege rest; do gdal_rasterize -a $i -te -180 -90 180 90 -ts 4320 2160 -a_srs EPSG:4326 -a_nodata -9999 -co "COMPRESS=LZW" -l spam2005v2r0_value_production PG:"dbname=djspamdata user=postgres" value-production/spam2005v2r0_value_of_production_${crops["${i:0:4}"]}_total.tiff; done;
for i in whea_i rice_i maiz_i barl_i pmil_i smil_i sorg_i ocer_i pota_i swpo_i yams_i cass_i orts_i bean_i chic_i cowp_i pige_i lent_i opul_i soyb_i grou_i cnut_i oilp_i sunf_i rape_i sesa_i ooil_i sugc_i sugb_i cott_i ofib_i acof_i rcof_i coco_i teas_i toba_i bana_i plnt_i trof_i temf_i vege_i rest_i ; do gdal_rasterize -a $i -te -180 -90 180 90 -ts 4320 2160 -a_srs EPSG:4326 -a_nodata -9999 -co "COMPRESS=LZW" -l spam2005v2r0_value_production PG:"dbname=djspamdata user=postgres" value-production/spam2005v2r0_value_of_production_${crops["${i:0:4}"]}_irrigated.tiff; done;
for i in whea_r rice_r maiz_r barl_r pmil_r smil_r sorg_r ocer_r pota_r swpo_r yams_r cass_r orts_r bean_r chic_r cowp_r pige_r lent_r opul_r soyb_r grou_r cnut_r oilp_r sunf_r rape_r sesa_r ooil_r sugc_r sugb_r cott_r ofib_r acof_r rcof_r coco_r teas_r toba_r bana_r plnt_r trof_r temf_r vege_r rest_r; do gdal_rasterize -a $i -te -180 -90 180 90 -ts 4320 2160 -a_srs EPSG:4326 -a_nodata -9999 -co "COMPRESS=LZW" -l spam2005v2r0_value_production PG:"dbname=djspamdata user=postgres" value-production/spam2005v2r0_value_of_production_${crops["${i:0:4}"]}_rainfed.tiff; done;

# local:
use /Applications/Postgres.app/Contents/Versions/9.3/bin/gdal_rasterize


/Applications/Postgres.app/Contents/Versions/9.3/bin/gdal_rasterize -a maiz -ot Float32 -te -180 -90 180 90 -ts 4320 2160 -a_srs EPSG:4326 -a_nodata -9999 -co "COMPRESS=LZW" -l spam2005v2r0_yield PG:"dbname=djspamdata user=postgres" maize_yield.tiff

#use qgis to create the nc files
